// <auto-generated />
using System;
using ApiVentas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiVentas.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiVentas.Models.ItemVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ItemVentas");
                });

            modelBuilder.Entity("ApiVentas.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemVentaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ItemVentaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ApiVentas.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ItemVentaId")
                        .HasColumnType("int");

                    b.Property<double>("MontoTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ItemVentaId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ApiVentas.Models.Producto", b =>
                {
                    b.HasOne("ApiVentas.Models.ItemVenta", null)
                        .WithMany("Productos")
                        .HasForeignKey("ItemVentaId");
                });

            modelBuilder.Entity("ApiVentas.Models.Venta", b =>
                {
                    b.HasOne("ApiVentas.Models.ItemVenta", null)
                        .WithMany("Ventas")
                        .HasForeignKey("ItemVentaId");
                });

            modelBuilder.Entity("ApiVentas.Models.ItemVenta", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
